added style to counter
isdi-coders-202207-bcn-coding-adventure/andrea-martinez-front pull request #3
Opened 2022-08-22 13:47 UTC by AndreaBitmind

2022-08-22 13:53 UTC, mariogl requested changes

2022-08-22 13:53 UTC, mariogl commented on src/index.tsx
> +import "@fontsource/oxanium";
El orden de la importación de CSS es incorrecto.

2022-08-22 13:57 UTC, mariogl commented
Haz que la web completa se vea bien: que el contador esté centrado, que todo el fondo sea del color de fondo del contador, y que el título de la web salga en blanco.

2022-08-22 14:09 UTC, AndreaBitmind commented on src/index.tsx
> +import "@fontsource/oxanium";
> Haz que la web completa se vea bien: que el contador esté centrado, que todo el fondo sea del color de fondo del contador, y que el título de la web salga en blanco.

en principio está todo corregido! ya tienes el push

2022-08-22 14:41 UTC, NachoLosada approved these changes
4. Dale la funcionalidad. Guarda la fecha clave en una constante que puedas usar en cualquier componente.

2022-08-22 14:42 UTC, NachoLosada approved these changes

2022-08-22 14:44 UTC, merged

2022-08-24 18:02 UTC, mariogl commented
@AndreaBitmind el contador tiene que estar centrado en el viewport, tanto en vertical como en horizontal.

2022-08-24 18:39 UTC, AndreaBitmind commented
Hecho! Ya tienes el pull hecho :)